## 라이브러리

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
import warnings
warnings.filterwarnings('ignore')

plt.rcParams['font.family'] = 'AppleGothic'
# plt.rcParams['font.family'] = 'NanumGothic'

## path 설정

In [2]:
path = '../..'
script_path = f'{path}/script'
word_path = f'{path}/words/final_datasets'

## 결과 데이터프레임 생성

In [3]:
if os.path.exists(f'{script_path}/csv_files/all_scripts_word_level_counts.csv'):
    df_result = pd.read_csv(f'{script_path}/csv_files/all_scripts_word_level_counts.csv', index_col='title')
else:
    df_result = pd.DataFrame(columns=['title', 'level_1', 'level_2', 'level_3', 'level_4', 'level_5', 'level_6']).set_index('title')

df_result

,level_1,level_2,level_3,level_4,level_5,level_6
title,,,,,,
13TH,3732,833,606,115,44,44
About.Time,3220,317,257,47,27,14
Arthur.Christmas,2293,228,240,106,49,39
Baby.Driver,2849,246,351,77,21,43
Bad.Boys,3707,344,392,94,57,40
Bee.Movie,2940,421,379,76,30,62
Ben.Platt.Live.from.Radio.City.Music.Hall,1157,76,78,12,7,14
Bo.Burnham_.Inside,983,117,70,11,5,8
Bo.Burnham_.Make.Happy,1165,119,137,22,21,20
Chasing.Coral,2526,300,439,54,21,25
Constantine,1809,202,217,34,22,17
Dave.Chappelle_.Sticks.&.Stones,2203,217,247,40,33,32
Dave.Chappelle_.Sticks._.Stones,2357,217,251,35,29,32
David.Attenborough_.A.Life.on.Our.Planet,2035,413,384,59,15,22
Disclosure,3793,425,520,90,53,91
Dolittle,2120,279,240,65,24,29
Dracula.Untold,1162,146,156,39,7,2
Enola.Holmes,2616,342,270,62,25,22
FYRE_.The.Greatest.Party.That.Never.Happened,4679,576,431,78,36,56
Heroin(e),1318,162,117,32,7,10
How.to.Be.Single,3698,285,267,64,57,28
In.Time,2094,194,116,23,1,7
Inception,3819,321,215,118,26,20
Inside.Job,3689,1192,801,72,27,44
Interstellar,4158,572,524,107,43,79
It_s.Complicated,3606,243,219,44,18,18
Jumanji_.Welcome.to.the.Jungle,3014,283,330,73,31,40
Kill.Bill_.Vol..1,1011,127,161,31,34,18
Kiss.the.Ground,2571,557,519,92,36,63
Klaus,2433,168,155,72,24,26
Knock.Down.The.House,2393,386,203,41,12,19
Kung.Fu.Panda,1514,176,140,61,4,20
Kung.Fu.Panda.2,1556,176,137,77,17,21
Kung.Fu.Panda.3,2052,177,148,91,26,21
Madagascar_.Escape.2.Africa,2610,268,248,62,23,35
Matilda,2205,210,202,43,34,43
Monty.Python.and.the.Holy.Grail,1816,279,310,96,21,58
Morning.Glory,3917,422,352,80,47,75
Notting.Hill,3338,321,276,60,45,32
Passengers,2100,204,201,26,16,42
Penguins.of.Madagascar_.The.Movie,2030,329,384,91,32,47
Prisoners,3027,200,216,41,12,14
Seaspiracy,4078,670,776,98,46,45
Second.Act,3333,336,248,52,34,30
The.Accountant,2751,428,370,68,28,38
The.Boy.in.the.Striped.Pajamas,1243,137,89,25,2,7
The.Dark.Knight,4162,490,430,70,57,44
The.Departed,4243,428,653,126,37,47
The.Family.Man,3386,285,216,59,18,17
The.Intern,4910,382,306,55,34,46
The.Judge,3459,396,299,142,26,35
The.Revenant,1778,186,164,84,19,7
The.Social.Dilemma,3870,600,489,64,48,35
The.Truman.Show,2261,164,146,74,10,8
There.Will.Be.Blood,2898,230,258,44,12,38
Three.Identical.Strangers,3116,283,247,37,38,21
Virunga,1580,243,158,49,11,16
What.the.Health,5126,824,870,124,107,93
Zodiac,5421,529,421,137,49,64

## 자막(단어) 파일 불러오기

### 경로 설정

In [4]:
# 다큐멘터리(0), 드라마(1), 영화(2) 선택
category = 2
if category == 0:
    script_path_cat = script_path + '/Documentary'
elif category == 1:
    script_path_cat = script_path + '/Drama'
else:
    script_path_cat = script_path + '/Movie'

_list = os.listdir(script_path_cat)

file_list = []
for file in _list:
    if file.startswith('.'): continue
    file_list.append(file)

file_list = sorted(file_list)
print(f'작품개수: {len(file_list)}')
count = 0
for index, title in enumerate(file_list):
    print(f'[{index}: {title}]', end=', ')
    count += 1
    if count%5 == 0:
        print()

작품개수: 41
[0: About.Time], [1: Arthur.Christmas], [2: Baby.Driver], [3: Bad.Boys], [4: Bee.Movie],
[5: Ben.Platt.Live.from.Radio.City.Music.Hall], [6: Constantine], [7: Dolittle], [8: Dracula.Untold], [9: Enola.Holmes],
[10: How.to.Be.Single], [11: In.Time], [12: Inception], [13: Interstellar], [14: It_s.Complicated],
[15: Jumanji_.Welcome.to.the.Jungle], [16: Kill.Bill_.Vol..1], [17: Klaus], [18: Kung.Fu.Panda], [19: Kung.Fu.Panda.2],
[20: Kung.Fu.Panda.3], [21: Madagascar_.Escape.2.Africa], [22: Matilda], [23: Monty.Python.and.the.Holy.Grail], [24: Morning.Glory],
[25: Notting.Hill], [26: Passengers], [27: Penguins.of.Madagascar_.The.Movie], [28: Prisoners], [29: Second.Act],
[30: The.Accountant], [31: The.Boy.in.the.Striped.Pajamas], [32: The.Dark.Knight], [33: The.Departed], [34: The.Family.Man],
[35: The.Intern], [36: The.Judge], [37: The.Revenant], [38: The.Truman.Show], [39: There.Will.Be.Blood],
[40: Zodiac],

### 작품 선택

In [5]:
# 바로 위 코드에서 file_list를 참고하여 작품 선택
title = file_list[0]
if (df_result.index == title).any(): print(f'{title} is already exists')
file_name = 'unique_words_' + title + '.WEBRip.Netflix.en[cc]'
print(f'{script_path_cat}/{title}/{file_name}')

About.Time is already exists
../../script/Movie/About.Time/unique_words_About.Time.WEBRip.Netflix.en[cc]

## unique_words_작품.csv to DataFrame

In [6]:
counts_df = pd.read_csv(f'{script_path_cat}/{title}/{file_name}.csv', index_col='word')
display(counts_df.info(), counts_df)

<class 'pandas.core.frame.DataFrame'>
Index: 1304 entries, just to zip
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   counts  1304 non-null   int64
dtypes: int64(1)
memory usage: 20.4+ KB

None

              counts
word
just              66
so                62
very              44
know              43
think             38
...              ...
impeccably         1
impressive         1
incredibly         1
indifference       1
zip                1

[1304 rows x 1 columns]

## 변형형을 원형으로 변환 후 다시 세기

In [7]:
# 단어 리스트 불러오기
pd.options.display.float_format = '{:.0f}'.format

word_db_df = pd.read_csv(f'{word_path}/words_df_word_level_final.csv')
word_db_df
word_db_df.set_index('Word', inplace=True)

#변형어 리스트 불러오기
existing_lemmas = pd.read_csv(f'{word_path}/existing_lemmas_final.csv', index_col='Word')
lemmas_dict = {}
for index, row in existing_lemmas.iterrows():
    lemmas = row["Lemmas"].split(';')
    for lemma in lemmas:
        lemmas_dict[lemma] = str(index)

def convertToHeadForm(word):
    word = str(word)
    head = lemmas_dict.get(word)
    # If a lemma word, change to head word in word list
    if head:
        return head
    if word in word_db_df.index:
        return word
    else:
        # Check if adverb
        if word.endswith('ly'):
            if word[:-2] in word_db_df.index:
                print(word[:-2])
                return word[:-2]
            if word.endswith('ily'):
                if (word[:-3] + 'y') in word_db_df.index:
                    print(word[:-3] + 'y')
                    return word[:-3] + 'y'
            if word.endswith('ally'):
                if (word[:-4]) in word_db_df.index:
                    print(word[:-4])
                    return word[:-4]
            if (word[:-2] + 'e') in word_db_df.index:
                print(word[:-2] + 'e')
                return word[:-2] + 'e'
        return word

counts_df.index = counts_df.index.map(convertToHeadForm)
counts_df

counts_df_headed = counts_df.groupby(counts_df.index).sum()
counts_df_headed.sort_values('counts', ascending=False, inplace=True)

counts_df_headed
# counts_df_headed.to_csv('test-about-time.csv')

             counts
word
just             66
so               62
can              62
think            54
good             54
...             ...
illustrious       1
imagination       1
imagine           1
immediate         1
zip               1

[1073 rows x 1 columns]

## word_level 컬럼 추가

In [8]:
counts_df_headed_joined = counts_df_headed.join(word_db_df[['word_level']])

counts_df_headed_joined

             counts  word_level
word
just             66           1
so               62           1
can              62           1
think            54           1
good             54           1
...             ...         ...
illustrious       1           4
imagination       1           2
imagine           1           1
immediate         1           2
zip               1           3

[1073 rows x 2 columns]

## Group by word_level

In [9]:
result = counts_df_headed_joined.groupby('word_level').sum('counts').transpose()
result['title'] = title
result = result.set_index('title')
result = result.rename(columns={1: 'level_1', 2: 'level_2', 3: 'level_3', 4: 'level_4', 5: 'level_5', 6: 'level_6'})
result

word_level  level_1  level_2  level_3  level_4  level_5  level_6
title
About.Time     3220      317      257       47       27       14

## df_result에 추가

In [10]:
df_result = pd.concat([df_result, result])
df_result

,level_1,level_2,level_3,level_4,level_5,level_6
title,,,,,,
13TH,3732,833,606,115,44,44
About.Time,3220,317,257,47,27,14
Arthur.Christmas,2293,228,240,106,49,39
Baby.Driver,2849,246,351,77,21,43
Bad.Boys,3707,344,392,94,57,40
Bee.Movie,2940,421,379,76,30,62
Ben.Platt.Live.from.Radio.City.Music.Hall,1157,76,78,12,7,14
Bo.Burnham_.Inside,983,117,70,11,5,8
Bo.Burnham_.Make.Happy,1165,119,137,22,21,20
Chasing.Coral,2526,300,439,54,21,25
Constantine,1809,202,217,34,22,17
Dave.Chappelle_.Sticks.&.Stones,2203,217,247,40,33,32
Dave.Chappelle_.Sticks._.Stones,2357,217,251,35,29,32
David.Attenborough_.A.Life.on.Our.Planet,2035,413,384,59,15,22
Disclosure,3793,425,520,90,53,91
Dolittle,2120,279,240,65,24,29
Dracula.Untold,1162,146,156,39,7,2
Enola.Holmes,2616,342,270,62,25,22
FYRE_.The.Greatest.Party.That.Never.Happened,4679,576,431,78,36,56
Heroin(e),1318,162,117,32,7,10
How.to.Be.Single,3698,285,267,64,57,28
In.Time,2094,194,116,23,1,7
Inception,3819,321,215,118,26,20
Inside.Job,3689,1192,801,72,27,44
Interstellar,4158,572,524,107,43,79
It_s.Complicated,3606,243,219,44,18,18
Jumanji_.Welcome.to.the.Jungle,3014,283,330,73,31,40
Kill.Bill_.Vol..1,1011,127,161,31,34,18
Kiss.the.Ground,2571,557,519,92,36,63
Klaus,2433,168,155,72,24,26
Knock.Down.The.House,2393,386,203,41,12,19
Kung.Fu.Panda,1514,176,140,61,4,20
Kung.Fu.Panda.2,1556,176,137,77,17,21
Kung.Fu.Panda.3,2052,177,148,91,26,21
Madagascar_.Escape.2.Africa,2610,268,248,62,23,35
Matilda,2205,210,202,43,34,43
Monty.Python.and.the.Holy.Grail,1816,279,310,96,21,58
Morning.Glory,3917,422,352,80,47,75
Notting.Hill,3338,321,276,60,45,32
Passengers,2100,204,201,26,16,42
Penguins.of.Madagascar_.The.Movie,2030,329,384,91,32,47
Prisoners,3027,200,216,41,12,14
Seaspiracy,4078,670,776,98,46,45
Second.Act,3333,336,248,52,34,30
The.Accountant,2751,428,370,68,28,38
The.Boy.in.the.Striped.Pajamas,1243,137,89,25,2,7
The.Dark.Knight,4162,490,430,70,57,44
The.Departed,4243,428,653,126,37,47
The.Family.Man,3386,285,216,59,18,17
The.Intern,4910,382,306,55,34,46
The.Judge,3459,396,299,142,26,35
The.Revenant,1778,186,164,84,19,7
The.Social.Dilemma,3870,600,489,64,48,35
The.Truman.Show,2261,164,146,74,10,8
There.Will.Be.Blood,2898,230,258,44,12,38
Three.Identical.Strangers,3116,283,247,37,38,21
Virunga,1580,243,158,49,11,16
What.the.Health,5126,824,870,124,107,93
Zodiac,5421,529,421,137,49,64

# 위의 코드들 합쳐서 한 번에 모든 작품 돌리기

In [21]:
import os
import pandas as pd
import numpy as np
# import seaborn as sns
# import matplotlib.pyplot as plt
# import matplotlib as mpl
# import warnings
# warnings.filterwarnings('ignore')

# plt.rcParams['font.family'] = 'AppleGothic'
# plt.rcParams['font.family'] = 'NanumGothic'

path = '../..'
script_path = f'{path}/script'
word_path = f'{path}/words/final_datasets'

if os.path.exists(f'{script_path}/csv_files/all_scripts_word_level_counts.csv'):
    df_result = pd.read_csv(f'{script_path}/csv_files/all_scripts_word_level_counts.csv', index_col='title')
else:
    df_result = pd.DataFrame(columns=['title', 'level_1', 'level_2', 'level_3', 'level_4', 'level_5', 'level_6']).set_index('title')

display(df_result)

# 다큐멘터리(0), 드라마(1), 영화(2) 선택
category = 2
if category == 0:
    script_path_cat = script_path + '/Documentary'
elif category == 1:
    script_path_cat = script_path + '/Drama'
else:
    script_path_cat = script_path + '/Movie'

_list = os.listdir(script_path_cat)

file_list = []
for file in _list:
    if file.startswith('.'): continue
    file_list.append(file)

file_list = sorted(file_list)
print(f'작품개수: {len(file_list)}')
count = 0
for index, title in enumerate(file_list):
    print(f'[{index}: {title}]', end=', ')
    count += 1
    if count%5 == 0:
        print()

Empty DataFrame
Columns: [level_1, level_2, level_3, level_4, level_5, level_6, running_time, WPS_mean, WPS_std, WPS_min, WPS_max, calculated, final_score]
Index: []

작품개수: 41
[0: About.Time], [1: Arthur.Christmas], [2: Baby.Driver], [3: Bad.Boys], [4: Bee.Movie],
[5: Ben.Platt.Live.from.Radio.City.Music.Hall], [6: Constantine], [7: Dolittle], [8: Dracula.Untold], [9: Enola.Holmes],
[10: How.to.Be.Single], [11: In.Time], [12: Inception], [13: Interstellar], [14: It_s.Complicated],
[15: Jumanji_.Welcome.to.the.Jungle], [16: Kill.Bill_.Vol..1], [17: Klaus], [18: Kung.Fu.Panda], [19: Kung.Fu.Panda.2],
[20: Kung.Fu.Panda.3], [21: Madagascar_.Escape.2.Africa], [22: Matilda], [23: Monty.Python.and.the.Holy.Grail], [24: Morning.Glory],
[25: Notting.Hill], [26: Passengers], [27: Penguins.of.Madagascar_.The.Movie], [28: Prisoners], [29: Second.Act],
[30: The.Accountant], [31: The.Boy.in.the.Striped.Pajamas], [32: The.Dark.Knight], [33: The.Departed], [34: The.Family.Man],
[35: The.Intern], [36: The.Judge], [37: The.Revenant], [38: The.Truman.Show], [39: There.Will.Be.Blood],
[40: Zodiac],

In [91]:
for i in range(len(file_list)):
    # 바로 위 코드에서 file_list를 참고하여 작품 선택
    title = file_list[i]
    if (df_result.index == title).any(): continue

    file_name = 'unique_words_' + title + '.WEBRip.Netflix.en[cc]'
    # print(f'{script_path_cat}/{title}/{file_name}')

    counts_df = pd.read_csv(f'{script_path_cat}/{title}/{file_name}.csv', index_col='word')

    # 단어 리스트 불러오기
    pd.options.display.float_format = '{:.0f}'.format

    word_db_df = pd.read_csv(f'{word_path}/words_df_word_level_final.csv')
    word_db_df.set_index('Word', inplace=True)

    #변형어 리스트 불러오기
    existing_lemmas = pd.read_csv(f'{word_path}/existing_lemmas_final.csv', index_col='Word')
    lemmas_dict = {}
    for index, row in existing_lemmas.iterrows():
        lemmas = row["Lemmas"].split(';')
        for lemma in lemmas:
            lemmas_dict[lemma] = str(index)

    def convertToHeadForm(word):
        word = str(word)
        head = lemmas_dict.get(word)
        # If a lemma word, change to head word in word list
        if head:
            return head
        if word in word_db_df.index:
            return word
        else:
            # Check if adverb
            if word.endswith('ly'):
                if word[:-2] in word_db_df.index:
                    # print(word[:-2])
                    return word[:-2]
                if word.endswith('ily'):
                    if (word[:-3] + 'y') in word_db_df.index:
                        # print(word[:-3] + 'y')
                        return word[:-3] + 'y'
                if word.endswith('ally'):
                    if (word[:-4]) in word_db_df.index:
                        # print(word[:-4])
                        return word[:-4]
                if (word[:-2] + 'e') in word_db_df.index:
                    # print(word[:-2] + 'e')
                    return word[:-2] + 'e'
            return word

    counts_df.index = counts_df.index.map(convertToHeadForm)

    counts_df_headed = counts_df.groupby(counts_df.index).sum()
    counts_df_headed.sort_values('counts', ascending=False, inplace=True)

    counts_df_headed_joined = counts_df_headed.join(word_db_df[['word_level']])

    result = counts_df_headed_joined.groupby('word_level').sum('counts').transpose()
    result['title'] = title
    result = result.set_index('title')
    result = result.rename(columns={1: 'level_1', 2: 'level_2', 3: 'level_3', 4: 'level_4', 5: 'level_5', 6: 'level_6'})

    df_result = pd.concat([df_result, result])

df_result

,level_1,level_2,level_3,level_4,level_5,level_6,running_time,WPS,calculated,final_score
title,,,,,,,,,,
About.Time,645,201,104,59,24,13,NaN,NaN,NaN,NaN
Arthur.Christmas,564,175,104,54,40,28,NaN,NaN,NaN,NaN
Baby.Driver,604,165,122,46,23,24,NaN,NaN,NaN,NaN
Bad.Boys,613,197,108,41,35,29,NaN,NaN,NaN,NaN
Bee.Movie,654,230,156,70,28,43,NaN,NaN,NaN,NaN
Ben.Platt.Live.from.Radio.City.Music.Hall,355,67,37,18,9,7,NaN,NaN,NaN,NaN
Constantine,498,143,89,40,18,16,NaN,NaN,NaN,NaN
Dolittle,586,217,109,55,25,24,NaN,NaN,NaN,NaN
Dracula.Untold,371,124,65,37,6,2,NaN,NaN,NaN,NaN
Enola.Holmes,627,223,117,51,26,21,NaN,NaN,NaN,NaN
How.to.Be.Single,618,188,107,33,37,21,NaN,NaN,NaN,NaN
In.Time,440,126,46,20,1,6,NaN,NaN,NaN,NaN
Inception,567,181,89,21,13,13,NaN,NaN,NaN,NaN
Interstellar,709,309,174,49,44,47,NaN,NaN,NaN,NaN
It_s.Complicated,617,160,96,37,24,15,NaN,NaN,NaN,NaN
Jumanji_.Welcome.to.the.Jungle,578,166,106,45,22,25,NaN,NaN,NaN,NaN
Kill.Bill_.Vol..1,387,110,67,31,17,14,NaN,NaN,NaN,NaN
Klaus,543,128,67,52,24,21,NaN,NaN,NaN,NaN
Kung.Fu.Panda,415,119,65,24,6,11,NaN,NaN,NaN,NaN
Kung.Fu.Panda.2,439,124,46,37,14,12,NaN,NaN,NaN,NaN
Kung.Fu.Panda.3,444,100,65,30,16,15,NaN,NaN,NaN,NaN
Madagascar_.Escape.2.Africa,572,186,95,44,25,29,NaN,NaN,NaN,NaN
Matilda,609,159,92,43,28,39,NaN,NaN,NaN,NaN
Monty.Python.and.the.Holy.Grail,516,197,89,76,15,30,NaN,NaN,NaN,NaN
Morning.Glory,722,252,154,70,44,53,NaN,NaN,NaN,NaN
Notting.Hill,681,215,118,54,34,21,NaN,NaN,NaN,NaN
Passengers,529,138,82,10,19,19,NaN,NaN,NaN,NaN
Penguins.of.Madagascar_.The.Movie,574,186,145,55,28,39,NaN,NaN,NaN,NaN
Prisoners,526,129,67,36,10,12,NaN,NaN,NaN,NaN
Second.Act,699,210,129,34,37,25,NaN,NaN,NaN,NaN
The.Accountant,755,254,173,43,37,30,NaN,NaN,NaN,NaN
The.Boy.in.the.Striped.Pajamas,383,92,34,18,3,6,NaN,NaN,NaN,NaN
The.Dark.Knight,747,311,177,68,43,30,NaN,NaN,NaN,NaN
The.Departed,719,250,154,57,38,32,NaN,NaN,NaN,NaN
The.Family.Man,657,187,108,42,23,13,NaN,NaN,NaN,NaN
The.Intern,736,216,130,37,40,31,NaN,NaN,NaN,NaN
The.Judge,639,210,133,60,24,27,NaN,NaN,NaN,NaN
The.Revenant,437,97,62,19,11,7,NaN,NaN,NaN,NaN
The.Truman.Show,517,115,75,27,14,7,NaN,NaN,NaN,NaN
There.Will.Be.Blood,525,150,76,27,8,18,NaN,NaN,NaN,NaN
Zodiac,825,268,172,72,45,41,NaN,NaN,NaN,NaN

## csv파일로 변환

In [1]:
df_result = df_result.sort_index()
df_result.to_csv(f'{script_path}/csv_files/all_scripts_word_level_counts.csv')

NameError: name 'df_result' is not defined