## 라이브러리

In [49]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
import warnings
warnings.filterwarnings('ignore')

## path 설정

In [50]:
path = '../..'
# path = 
word_path = f'{path}/words/final_datasets'

## 파일 불러오기

In [51]:
df = pd.read_csv(f'{word_path}/all_scripts.csv').set_index('title')
df

,level_1,level_2,level_3,level_4,level_5,level_6,WPS_mean,WPS_std,WPS_min,WPS_max,running_time(sec),weight
title,,,,,,,,,,,,
13TH,789,371,252,85,43,28,2.961973,0.793955,1.065530,5.997001,5744.280,0.626710
About.Time,645,201,104,59,24,13,2.182928,1.094544,0.503440,6.080000,6962.126,0.517083
Anne.with.an.E,946,493,282,228,60,93,3.098348,0.945341,0.592066,6.849315,20562.876,0.175073
Arthur.Christmas,564,175,104,54,40,28,2.156860,0.925752,0.510204,5.263158,5404.775,0.666078
Baby.Driver,604,165,122,46,23,24,2.833974,1.249704,0.574053,10.657194,6654.023,0.541026
...,...,...,...,...,...,...,...,...,...,...,...,...
There.Will.Be.Blood,525,150,76,27,8,18,2.341123,1.015496,0.564175,6.594724,8764.213,0.410761
Three.Identical.Strangers,650,195,108,33,26,18,3.051841,1.033558,0.736594,7.733952,5542.412,0.649537
Virunga,526,157,74,21,11,7,2.318065,0.882764,0.625000,6.818182,5492.720,0.655413
What.the.Health,844,350,263,78,80,55,3.100264,0.851034,0.799041,7.084469,5342.963,0.673783
Zodiac,825,268,172,72,45,41,3.030728,0.970173,0.538117,7.377805,9250.533,0.389167

## level_1 ~ level_6까지 weight 적용

In [52]:
df_calculated = df.copy()
for i in range(1, 7):
    level = 'level_' + str(i)
    df_calculated[level] = df_calculated[level] * df_calculated['weight']

df_calculated

,level_1,level_2,level_3,level_4,level_5,level_6,WPS_mean,WPS_std,WPS_min,WPS_max,running_time(sec),weight
title,,,,,,,,,,,,
13TH,494.474503,232.509557,157.931020,53.270384,26.948547,17.547891,2.961973,0.793955,1.065530,5.997001,5744.280,0.626710
About.Time,333.518813,103.933770,53.776677,30.507922,12.410002,6.722085,2.182928,1.094544,0.503440,6.080000,6962.126,0.517083
Anne.with.an.E,165.618856,86.310884,49.370526,39.916595,10.504367,16.281769,3.098348,0.945341,0.592066,6.849315,20562.876,0.175073
Arthur.Christmas,375.667812,116.563594,69.272079,35.968195,26.643107,18.650175,2.156860,0.925752,0.510204,5.263158,5404.775,0.666078
Baby.Driver,326.779754,89.269304,66.005182,24.887200,12.443600,12.984626,2.833974,1.249704,0.574053,10.657194,6654.023,0.541026
...,...,...,...,...,...,...,...,...,...,...,...,...
There.Will.Be.Blood,215.649711,61.614203,31.217863,11.090557,3.286091,7.393704,2.341123,1.015496,0.564175,6.594724,8764.213,0.410761
Three.Identical.Strangers,422.198855,126.659656,70.149964,21.434711,16.887954,11.691661,3.051841,1.033558,0.736594,7.733952,5542.412,0.649537
Virunga,344.747229,102.899838,48.500561,13.763673,7.209543,4.587891,2.318065,0.882764,0.625000,6.818182,5492.720,0.655413
What.the.Health,568.673225,235.824205,177.205045,52.555108,53.902675,37.058089,3.100264,0.851034,0.799041,7.084469,5342.963,0.673783
Zodiac,321.062581,104.296693,66.936684,28.020007,17.512504,15.955837,3.030728,0.970173,0.538117,7.377805,9250.533,0.389167

In [53]:
df_calculated.describe()

,level_1,level_2,level_3,level_4,level_5,level_6,WPS_mean,WPS_std,WPS_min,WPS_max,running_time(sec),weight
count,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000,73.000000
mean,328.878202,112.916920,66.615375,25.321796,15.864870,13.995773,2.826001,1.023957,0.646922,7.215549,8962.705822,0.547424
std,115.033850,46.525931,31.979723,11.224639,8.757927,7.690630,0.412360,0.169915,0.155569,1.945292,6473.631014,0.249913
min,126.925737,41.301469,21.743435,5.819541,0.590696,1.429082,2.036550,0.536389,0.500000,4.388926,2198.946000,0.126190
25%,253.703415,78.999459,47.022058,18.275557,10.415554,7.956486,2.507442,0.914534,0.521241,6.134969,5342.963000,0.418590
50%,325.496293,103.852315,60.565889,23.859633,16.099003,13.316496,2.841146,1.009966,0.591891,6.818182,6160.988000,0.584322
75%,406.968827,134.957963,75.363685,30.507922,19.505494,17.547891,3.127005,1.125255,0.723365,7.677543,8600.300000,0.673783
max,659.770636,235.824205,177.205045,56.893720,53.902675,37.058089,3.827371,1.375000,1.141553,17.471410,28528.501000,1.637148

## 정규화

In [54]:
df_calculated_level = df_calculated[['level_1', 'level_2', 'level_3', 'level_4', 'level_5', 'level_6']]
df_normalization = (df_calculated_level - df_calculated_level.min()) / (df_calculated_level.max() - df_calculated_level.min())
df_normalization

,level_1,level_2,level_3,level_4,level_5,level_6
title,,,,,,
13TH,0.689786,0.982960,0.876021,0.929057,0.494408,0.452407
About.Time,0.387717,0.321979,0.206052,0.483383,0.221701,0.148559
Anne.with.an.E,0.072616,0.231384,0.177710,0.667599,0.185956,0.416871
Arthur.Christmas,0.466819,0.386907,0.305726,0.590291,0.488678,0.483345
Baby.Driver,0.375070,0.246592,0.284712,0.373333,0.222331,0.324330
...,...,...,...,...,...,...
There.Will.Be.Blood,0.166510,0.104423,0.060944,0.103203,0.050559,0.167409
Three.Identical.Strangers,0.554145,0.438808,0.311373,0.305735,0.305696,0.288040
Virunga,0.408790,0.316664,0.172114,0.155541,0.124153,0.088658
What.the.Health,0.829036,1.000000,1.000000,0.915053,1.000000,1.000000
Zodiac,0.364340,0.323845,0.290704,0.434671,0.317411,0.407723

In [55]:
df_result = df_normalization.join(df[['WPS_mean','WPS_std', 'WPS_min', 'WPS_max']])
df_result

,level_1,level_2,level_3,level_4,level_5,level_6,WPS_mean,WPS_std,WPS_min,WPS_max
title,,,,,,,,,,
13TH,0.689786,0.982960,0.876021,0.929057,0.494408,0.452407,2.961973,0.793955,1.065530,5.997001
About.Time,0.387717,0.321979,0.206052,0.483383,0.221701,0.148559,2.182928,1.094544,0.503440,6.080000
Anne.with.an.E,0.072616,0.231384,0.177710,0.667599,0.185956,0.416871,3.098348,0.945341,0.592066,6.849315
Arthur.Christmas,0.466819,0.386907,0.305726,0.590291,0.488678,0.483345,2.156860,0.925752,0.510204,5.263158
Baby.Driver,0.375070,0.246592,0.284712,0.373333,0.222331,0.324330,2.833974,1.249704,0.574053,10.657194
...,...,...,...,...,...,...,...,...,...,...
There.Will.Be.Blood,0.166510,0.104423,0.060944,0.103203,0.050559,0.167409,2.341123,1.015496,0.564175,6.594724
Three.Identical.Strangers,0.554145,0.438808,0.311373,0.305735,0.305696,0.288040,3.051841,1.033558,0.736594,7.733952
Virunga,0.408790,0.316664,0.172114,0.155541,0.124153,0.088658,2.318065,0.882764,0.625000,6.818182
What.the.Health,0.829036,1.000000,1.000000,0.915053,1.000000,1.000000,3.100264,0.851034,0.799041,7.084469
Zodiac,0.364340,0.323845,0.290704,0.434671,0.317411,0.407723,3.030728,0.970173,0.538117,7.377805

## csv 파일로 변환

In [56]:
df_result.to_csv(f'{word_path}/all_scripts_normalization.csv')