## 라이브러리

In [56]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
import warnings
warnings.filterwarnings('ignore')

## path 설정

In [60]:
path = '../..'
script_path = f'{path}/script'
word_path = f'{path}/words/final_datasets'

## 결과 데이터프레임 생성

In [76]:
if os.path.exists(f'{word_path}/all_scripts_WPS.csv'):
    df_result = pd.read_csv(f'{word_path}/all_scripts_WPS.csv', index_col='title')
else:
    df_result = pd.DataFrame(columns=['title', 'mean', 'std', 'min', 'max']).set_index('title')

df_result

Empty DataFrame
Columns: [mean, std, min, max]
Index: []

## 파일 불러오기

In [62]:
import os

# 다큐멘터리(0), 드라마(1), 영화(2) 선택
category = 1
if category == 0:
    script_path_cat = script_path + '/Documentary'
elif category == 1:
    script_path_cat = script_path + '/Drama'
else:
    script_path_cat = script_path + '/Movie'

_list = os.listdir(script_path_cat)
file_list = []
for file in _list:
    if file.startswith('.'): continue
    file_list.append(file)

file_list = sorted(file_list)
print(f'작품개수: {len(file_list)}')
count = 0
for index, title in enumerate(file_list):
    print(f'[{index}: {title}]', end=', ')
    count += 1
    if count%5 == 0:
        print()

작품개수: 14
[0: Anne.with.an.E], [1: Better.Call.Saul], [2: Black.Mirror], [3: Breaking.Bad], [4: Disenchantment],
[5: Friends], [6: How.to.Get.Away.With.Murder], [7: MINDHUNTER], [8: Narcos], [9: Peaky.Blinders],
[10: Rick.and.Morty], [11: Sherlock], [12: Stranger.Things], [13: The.Good.Doctor],

## 여기서 작품 선택합니다 꼭!!

In [63]:
# 바로 위 코드에서 file_list를 참고하여 작품 선택
title = file_list[0]
if (df_result.index==title).any(): print(f'{title} is already exists')

file_name = title + '.WEBRip.Netflix.en[cc]'
print(f'{script_path_cat}/{title}/{file_name}')

../../script/Drama/The.Good.Doctor/The.Good.Doctor.WEBRip.Netflix.en[cc]

In [64]:
df_file = pd.read_csv(f'{script_path_cat}/{title}/{file_name}.csv')
df = df_file
display(df.info(), df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5784 entries, 0 to 5783
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   start   5784 non-null   object
 1   end     5784 non-null   object
 2   script  5784 non-null   object
dtypes: object(3)
memory usage: 135.7+ KB

None

,start,end,script
0,00:01:47.482,00:01:49.568,Boy: Mister?
1,00:01:49.610,00:01:51.236,Mister?
2,00:02:26.271,00:02:29.733,"Woman: Ladies and gentlemen, welcome to San Jo..."
3,00:02:56.802,00:03:01.515,Look out! Watch out!
4,00:03:01.556,00:03:02.766,Help!
...,...,...,...
5779,00:42:02.770,00:42:05.190,"I mean, he's not at the hospital."
5780,00:42:05.231,00:42:10.111,And there used to be a picture here of Shaun...
5781,00:42:10.153,00:42:12.613,"and his brother, Steve."
5782,00:42:14.282,00:42:15.908,What do you think that means?
5783,00:42:22.081,00:42:24.334,It means he's not coming back.

## 자막이 재생되는 시간 계산

In [65]:
df['start'] = pd.to_datetime(df['start'])
df['end'] = pd.to_datetime(df['end'])
df

,start,end,script
0,2021-10-07 00:01:47.482,2021-10-07 00:01:49.568,Boy: Mister?
1,2021-10-07 00:01:49.610,2021-10-07 00:01:51.236,Mister?
2,2021-10-07 00:02:26.271,2021-10-07 00:02:29.733,"Woman: Ladies and gentlemen, welcome to San Jo..."
3,2021-10-07 00:02:56.802,2021-10-07 00:03:01.515,Look out! Watch out!
4,2021-10-07 00:03:01.556,2021-10-07 00:03:02.766,Help!
...,...,...,...
5779,2021-10-07 00:42:02.770,2021-10-07 00:42:05.190,"I mean, he's not at the hospital."
5780,2021-10-07 00:42:05.231,2021-10-07 00:42:10.111,And there used to be a picture here of Shaun...
5781,2021-10-07 00:42:10.153,2021-10-07 00:42:12.613,"and his brother, Steve."
5782,2021-10-07 00:42:14.282,2021-10-07 00:42:15.908,What do you think that means?
5783,2021-10-07 00:42:22.081,2021-10-07 00:42:24.334,It means he's not coming back.

In [66]:
df['duration'] = df['end'] - df['start']
df['duration'] = df['duration'].astype('str')
df['duration'] = df['duration'].str.split(' ').str[2]
df['duration'] = df['duration'].str.split(':').str[2].astype('float')
display(df.info(), df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5784 entries, 0 to 5783
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   start     5784 non-null   datetime64[ns]
 1   end       5784 non-null   datetime64[ns]
 2   script    5784 non-null   object
 3   duration  5784 non-null   float64
dtypes: datetime64[ns](2), float64(1), object(1)
memory usage: 180.9+ KB

None

,start,end,script,duration
0,2021-10-07 00:01:47.482,2021-10-07 00:01:49.568,Boy: Mister?,2.086
1,2021-10-07 00:01:49.610,2021-10-07 00:01:51.236,Mister?,1.626
2,2021-10-07 00:02:26.271,2021-10-07 00:02:29.733,"Woman: Ladies and gentlemen, welcome to San Jo...",3.462
3,2021-10-07 00:02:56.802,2021-10-07 00:03:01.515,Look out! Watch out!,4.713
4,2021-10-07 00:03:01.556,2021-10-07 00:03:02.766,Help!,1.210

## 필요없는 컬럼 제거

In [67]:
df = df.drop(columns=['start', 'end'])
df.head()

                                              script  duration
0                                       Boy: Mister?     2.086
1                                            Mister?     1.626
2  Woman: Ladies and gentlemen, welcome to San Jo...     3.462
3                               Look out! Watch out!     4.713
4                                              Help!     1.210

## 단어의 개수 계산(띄어쓰기 기준)

In [68]:
df['words_num'] = df['script'].apply(lambda x: len(x.split(' ')))
df

                                                 script  duration  words_num
0                                          Boy: Mister?     2.086          2
1                                               Mister?     1.626          1
2     Woman: Ladies and gentlemen, welcome to San Jo...     3.462         10
3                                  Look out! Watch out!     4.713          4
4                                                 Help!     1.210          1
...                                                 ...       ...        ...
5779                  I mean, he's not at the hospital.     2.420          7
5780    And there used to be a picture here of Shaun...     4.880         10
5781                            and his brother, Steve.     2.460          4
5782                      What do you think that means?     1.626          6
5783                     It means he's not coming back.     2.253          6

[5784 rows x 3 columns]

# 1초에 몇 개의 단어가 보여지는지 계산

In [69]:
df['wordsPerSec'] = df['words_num'] / df['duration']
df['secPerWord'] = df['duration'] / df['words_num']
df

,script,duration,words_num,wordsPerSec,secPerWord
0,Boy: Mister?,2.086,2,0.958773,1.043000
1,Mister?,1.626,1,0.615006,1.626000
2,"Woman: Ladies and gentlemen, welcome to San Jo...",3.462,10,2.888504,0.346200
3,Look out! Watch out!,4.713,4,0.848716,1.178250
4,Help!,1.210,1,0.826446,1.210000
...,...,...,...,...,...
5779,"I mean, he's not at the hospital.",2.420,7,2.892562,0.345714
5780,And there used to be a picture here of Shaun...,4.880,10,2.049180,0.488000
5781,"and his brother, Steve.",2.460,4,1.626016,0.615000
5782,What do you think that means?,1.626,6,3.690037,0.271000
5783,It means he's not coming back.,2.253,6,2.663116,0.375500

## 이상치 제거
### 1. 1개의 단어로 된 문장 제거
### 2. Words Per Sec 값이 0.5 이하인 문장 제거

In [70]:
df = df[df['words_num']!=1]
df = df[df['wordsPerSec']>=0.5].sort_values('words_num')
df

,script,duration,words_num,wordsPerSec,secPerWord
0,Boy: Mister?,2.086,2,0.958773,1.043000
1279,"Yeah, uh...",1.627,2,1.229256,0.813500
1291,You're home.,2.294,2,0.871840,1.147000
1294,No! No!,2.794,2,0.715820,1.397000
1297,He promised!,2.378,2,0.841043,1.189000
...,...,...,...,...,...
127,I do also need a narrow six-foot tube and high...,10.595,38,3.586597,0.278816
2727,Evan was diagnosed with the flu eight months a...,10.636,39,3.666792,0.272718
3710,The differential diagnosis for biliary tree sc...,12.388,39,3.148208,0.317641
3366,You have to come up with a proposal for the ex...,10.594,40,3.775722,0.264850
829,I have a patient lying in the OR waiting for l...,9.801,42,4.285277,0.233357

## describe 보기

In [71]:
df.describe()

          duration    words_num  wordsPerSec   secPerWord
count  5338.000000  5338.000000  5338.000000  5338.000000
mean      2.611865     7.308168     2.908974     0.432899
std       1.541466     4.845680     1.259277     0.249069
min       0.709000     2.000000     0.521241     0.125100
25%       1.626000     4.000000     1.932927     0.268806
50%       2.210000     6.000000     2.813331     0.355452
75%       3.128000     9.000000     3.720161     0.517350
max      18.768000    42.000000     7.993605     1.918500

In [72]:
df = df.sort_values('wordsPerSec')
pd.set_option('min_rows', 10)
pd.set_option('max_rows', 10)
display(df.head(10), df.tail(10))

                 script  duration  words_num  wordsPerSec  secPerWord
3782      Just breathe.     3.837          2     0.521241      1.9185
5731         I'm sorry.     3.795          2     0.527009      1.8975
1404      Cashier: Hey!     3.753          2     0.532907      1.8765
5652            No, no.     3.712          2     0.538793      1.8560
4049       I-I'm sorry.     3.671          2     0.544811      1.8355
4865         Follow me.     3.629          2     0.551116      1.8145
4067             I did.     3.628          2     0.551268      1.8140
88         Hmm. Well...     3.546          2     0.564016      1.7730
5030         He's dead.     3.503          2     0.570939      1.7515
5514  Bartender says...     3.462          2     0.577701      1.7310

,script,duration,words_num,wordsPerSec,secPerWord
1243,I've got a pile-up on I-80 and four other vehi...,1.794,13,7.246377,0.138000
3715,That's the first time I've ever heard you say ...,1.377,10,7.262164,0.137700
890,I made sure not to say that.,0.959,7,7.299270,0.137000
5189,He's a pro. I don't know if I'd call him in at...,1.627,12,7.375538,0.135583
4501,We're gonna need a sponge stick to control the...,1.877,14,7.458711,0.134071
4236,"Come on, man. Just do what he says.",1.042,8,7.677543,0.130250
13,I have a fresh change of clothes in my bag.,1.293,10,7.733952,0.129300
2382,Your eyesight must a hell of a lot better than...,1.419,11,7.751938,0.129000
5191,He's one of the best in the world.,1.001,8,7.992008,0.125125
5496,I don't think he was trying to be the best.,1.251,10,7.993605,0.125100

In [73]:
df = df.sort_values('secPerWord')
df.tail(10)

                 script  duration  words_num  wordsPerSec  secPerWord
5514  Bartender says...     3.462          2     0.577701      1.7310
5030         He's dead.     3.503          2     0.570939      1.7515
88         Hmm. Well...     3.546          2     0.564016      1.7730
4067             I did.     3.628          2     0.551268      1.8140
4865         Follow me.     3.629          2     0.551116      1.8145
4049       I-I'm sorry.     3.671          2     0.544811      1.8355
5652            No, no.     3.712          2     0.538793      1.8560
1404      Cashier: Hey!     3.753          2     0.532907      1.8765
5731         I'm sorry.     3.795          2     0.527009      1.8975
3782      Just breathe.     3.837          2     0.521241      1.9185

In [74]:
result = df['wordsPerSec'].describe().to_frame().transpose()[['mean', 'std', 'min', 'max']]
result['title'] = title
result = result.set_index('title')
result

                     mean       std       min       max
title
The.Good.Doctor  2.908974  1.259277  0.521241  7.993605

## df_result에 합치기

In [75]:
df_result = pd.concat([df_result, result])
df_result

                     mean       std       min       max
title
The.Good.Doctor  2.908974  1.259277  0.521241  7.993605

# 위의 코드들 합쳐서 한 번에 모든 작품 돌리기

In [ ]:
import os
import pandas as pd
import numpy as np
# import seaborn as sns
# import matplotlib.pyplot as plt
# import matplotlib as mpl
# import warnings
# warnings.filterwarnings('ignore')

path = '../..'
# path = '/content/drive/MyDrive/elice_데이터분석_프로젝트/팀_공유_폴더'
script_path = f'{path}/script'
word_path = f'{path}/words/final_datasets'

if os.path.exists(f'{word_path}/all_scripts_WPS.csv'):
    df_result = pd.read_csv(f'{word_path}/all_scripts_WPS.csv', index_col='title')
else:
    df_result = pd.DataFrame(columns=['title', 'mean', 'std', 'min', 'max']).set_index('title')

display(df_result)

# 다큐멘터리(0), 드라마(1), 영화(2) 선택
category = 2
if category == 0:
    script_path_cat = script_path + '/Documentary'
elif category == 1:
    script_path_cat = script_path + '/Drama'
else:
    script_path_cat = script_path + '/Movie'

_list = os.listdir(script_path_cat)
file_list = []
for file in _list:
    if file.startswith('.'): continue
    file_list.append(file)

file_list = sorted(file_list)
print(f'작품개수: {len(file_list)}')
count = 0
for index, title in enumerate(file_list):
    print(f'[{index}: {title}]', end=', ')
    count += 1
    if count%5 == 0:
        print()

In [ ]:
for i in range(len(file_list)):
    # 바로 위 코드에서 file_list를 참고하여 작품 선택
    title = file_list[i]
    if (df_result.index==title).any(): continue

    file_name = title + '.WEBRip.Netflix.en[cc]'
    # print(f'{path}/{title}/{file_name}')

    df_file = pd.read_csv(f'{script_path_cat}/{title}/{file_name}.csv')
    df = df_file

    df['start'] = pd.to_datetime(df['start'])
    df['end'] = pd.to_datetime(df['end'])

    df['duration'] = df['end'] - df['start']
    df['duration'] = df['duration'].astype('str')
    df['duration'] = df['duration'].str.split(' ').str[2]
    df['duration'] = df['duration'].str.split(':').str[2].astype('float')

    df = df.drop(columns=['start', 'end'])

    df['words_num'] = df['script'].apply(lambda x: len(x.split(' ')))

    df['wordsPerSec'] = df['words_num'] / df['duration']
    df['secPerWord'] = df['duration'] / df['words_num']

    df = df[df['words_num']!=1]
    df = df[df['wordsPerSec']>=0.5].sort_values('words_num')

    result = df['wordsPerSec'].describe().to_frame().transpose()[['mean', 'std', 'min', 'max']]
    result['title'] = title
    result = result.set_index('title')

    df_result = pd.concat([df_result, result])

df_result

## CSV 파일로 변환

In [ ]:
df_result.to_csv(f'{word_path}/all_scripts_WPS.csv')